clients:
  - url: "http://192.168.150.141:3100/loki/api/v1/push"
    timeout: 30s

positions:
  filename: /var/log/positions.yaml

scrape_configs:
  - job_name: dummy_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog_journal
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: "(?P<log_type>kernel|systemd) (?P<content>.*)$"
