clients:
  - url: "http://192.168.150.141:3100/loki/api/v1/push"
    timeout: 30s

positions:
  filename: /var/log/positions.yaml

scrape_configs:

  - job_name: dummy_syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog_journal
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: "^(?P<time>[A-Z][a-z]{2} \\d{2} \\d{2}:\\d{2}:\\d{2}) (?P<hostname>\\S+) (?P<system>.+?): (?P<message>.*)"
      - labels:
          time:
          hostname:
          system:
